version: '3.9'
services:
  nginx:
    image: 'nginx:latest'
    volumes:
      - './nginx/:/etc/nginx/conf.d/'
    ports:
      - '8000:8000'
    depends_on:
      - app
  app:
    # build:
    #   context: .

    image: registry.gitlab.com/onur2660/dockerized-django/app:latest
    # image: app:latest
    volumes:
      - '.:/app'
    command: ls -a
    env_file:
      - env-$RTE
    depends_on:
      - db
  db:
    image: 'postgres:13-alpine'
    volumes:
      - 'dev-db-data:/var/lib/postgresql/data'
    env_file:
      - env-$RTE
volumes:
  dev-db-data: null
