___
#3 dashes shows it is .yml file

#Name that will appear in github actions
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04 #docker compose is pre installed
    steps:
      - name: Login to Docker Hub
        #this is a github action, which is a docker container and configuration setup to do a certain task @v1 = version
        uses: docker/login-action@v1
        width:
        #pass this into the login action
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrects.DOCKERHUB_TOKEN }}
      - name: Checkout #provided for free by github, it gives ACCESS to the code,
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"