---
# 3 dashes shows it is .yml file

# Name that will appear in GitHub Actions
name: Checks

on:
  push:

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04 # docker compose is pre-installed
    steps:
      - name: Login to Docker Hub
        # this is a GitHub Action, which is a Docker container and configuration setup to do a certain task @v1 = version
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        # provided for free by GitHub, it gives ACCESS to the code
        uses: actions/checkout@v2
      - name: Coverage
        # run: export RTE=dev;docker-compose run --rm app sh -c "coverage run --source="." --omit=manage.py manage.py test --verbosity 2 coverage report -m --fail-under=80"
        run: export RTE=dev;docker-compose run --rm app sh -c "coverage run --source='.' --omit=manage.py manage.py test --verbosity 2 && coverage report -m --fail-under=80"

      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
